### ISSUE TITLE
Some information

### ISSUE THREAD

**Issue by Angelk90** [aadilhasan/react-date-picker#1]
Hi @aadilhasan : 

1) How can I change the placeholder value after the user selects the date?

2) Would it be possible to start the months from 1 and not from 0?
It gives me several problems.

3) There is a way to get the date back to me in the format I want, without having to do something like this:

`    new Date(start).toLocaleDateString(),
`

4) A way to change the wording of the calendar, for example in another language.

Ex:
[codesandbox](https://codesandbox.io/s/adoring-mclean-hf7ku)

**Comment by aadilhasan** [comment]
Hey @Angelk90, Thanks for reporting these issues, actually I just made it in a hurry for some personal project, I guess there are some bugs, I will fix these ASAP and will enhance the features and will get back to you.

**Comment by aadilhasan** [comment]
@Angelk90 can you tell me what are issues you are facing with the month starting with 0?

**Comment by Angelk90** [comment]
@aadilhasan  : Normally in the calendars I used, the months range from 1 to 12, instead having the months ranging from 0 to 11 and inconvenient for me, because it uses information that is given to me to send it to the server, if the months start with 0 I have to  , read the given string, add +1 per month then send it.  especially the user who looks at the date written in the placeholder is confused.

In fact, the beginning looked at the placement on the placeholder believing you have wrong to select the month.

**Comment by aadilhasan** [comment]
@Angelk90  Hey, I have fixed the issues, and from now on user will only get date object, no custom object, and there are some api/props changes as well, please have a look before you use, it's not backward compatible. for now there is no language support, i am working on it.

**Comment by Angelk90** [comment]
@aadilhasan : 

I didn't understand what changes you made but the placeholder thing with the month still starting from zero I don't understand.

**Comment by aadilhasan** [comment]
@Angelk90 i made it uniform, everywhere, user will just get native date object only, from that date object if you try to get month it will start from 0, that is how native date works.

**Comment by Angelk90** [comment]
@aadilhasan  : 

can you give me an example where I can change how I want the placeholder of the input field, after selecting the dates?

**Comment by aadilhasan** [comment]
@Angelk90  here in demo there is an example with custom placeholder.
https://codesandbox.io/s/async-rain-m5m831xjk9

**Comment by Angelk90** [comment]
@aadilhasan : 
Not what I was saying, I was talking about changing the text into input.
The result I would like to have is this, considering that the selected month is October.

![Screenshot_20191017_092359](https://user-images.githubusercontent.com/20476002/66986881-f9b02080-f0bf-11e9-9284-c83c67ed9dbc.png)

**Comment by aadilhasan** [comment]
@Angelk90  ohh, i am so sorry, i did't see that, default placeholder is showing wrong month. I will fix it asap

**Comment by Angelk90** [comment]
@aadilhasan : 

Wait, what you see in the image is the result I would like to obtain.

**Comment by aadilhasan** [comment]
@Angelk90 i got it, thanks. I will fix it ASAP.

**Comment by Angelk90** [comment]
@aadilhasan : Is there any news?

**Comment by aadilhasan** [comment]
@Angelk90  Hey i fixed it with latest release.

**Comment by Angelk90** [comment]
@aadilhasan : 
If I wanted to change the separator symbol inside the input field?
The result I would like to achieve is this, as a separator "/":

![](https://user-images.githubusercontent.com/20476002/66986881-f9b02080-f0bf-11e9-9284-c83c67ed9dbc.png)

**Comment by Angelk90** [comment]
@aadilhasan : 
Take a look at this example:
https://codesandbox.io/s/react-range-picker-np165

**Comment by aadilhasan** [comment]
@Angelk90 i can just give you the functionality to change the date format. you won't be able to change the divider (~) is that fine ?

**Comment by Angelk90** [comment]
@aadilhasan  : Did you see example that I posted to you?

**Comment by aadilhasan** [comment]
Hey i have fixed dates related issues in recent release, please raise another issue if you find any other issues, closing this issue.
