### ISSUE TITLE
How to close the datepicker once the date is being picked?

### ISSUE THREAD

**Issue by jo-san** [aadilhasan/react-date-picker#10]
I would like to have an option to say closeOnChoose - kinda to avoid explicit click on `select` CTA to choose date in `disableRange` mode at-least where it makes more sense to it.

**Comment by aadilhasan** [comment]
@jo-san thanks you for the feedback, i am already working on these.

**Comment by aadilhasan** [comment]
@jo-san  Thank you so much for the suggestion i am already working on that, and please accept my apologies for not being able to respond quick enough.

**Comment by aadilhasan** [comment]
@jo-san  i have added this feature in the latest release, so closing this issue.
