### ISSUE TITLE
endDate in range has wrong value

### ISSUE THREAD

**Issue by lyvija** [aadilhasan/react-date-picker#12]
Hey, I'm trying to create filter for my app using react-range-picker. I've got a bug after choosing date range - enddate is wrong, about 1 and half month forward, sometimes 2 months. Dont know when or why it exactly happend, sometimes it works and then not. Thank you in advance for any idea how to solve this.

handleRange = (date1, date2) => {
//date2 has wrong value here already
}} 
return(
--<RangePicker className='range'
      dateFormat='dd.mm.yyyy'
      onClose={handleRange}
      rangeTillEndOfDay={true}
--/>
)

Prtscr example:
![Screenshot from 2020-02-13 14-21-50](https://user-images.githubusercontent.com/26010477/74439534-b185ec80-4e6c-11ea-9711-6b55c8a3f294.png)

**Comment by lyvija** [comment]
I found out, that problem starts on doubleclick. Then all endDates are wrong.

**Comment by aadilhasan** [comment]
@lyvija Thank you so much for reporting the issue, i will look into it and fix it ASAP, and please accept my apologies for not being able to respond quick enough.

**Comment by aadilhasan** [comment]
@lyvija  i am not able to reproduce the issue can you please attach some video/gif or something when it is happening.

**Comment by lyvija** [comment]
@aadilhasan  Hey, it is ok. I was forced to use another datepicker because I have deadline. But I'll checkout my previous commit if i would have more time and post some demo of this problem. 
Simply,  when I chose the date by double-click, the second date was wrong and every other date as well, although I did not choose just one day but the range. F.e. I chose 12. feb by double-click : first date was 12. feb and second was some date in march. Then, when I chose 12.feb - 14.feb first date was right and second was march again. But before using double-click everything worked.

**Comment by aadilhasan** [comment]
@lyvija ok, let me see if i can reproduce it, can you reproduce it here [https://codesandbox.io/s/async-rain-m5m831xjk9](https://codesandbox.io/s/async-rain-m5m831xjk9) it will be easy, and please send me the link once done.

**Comment by Kadrangelion** [comment]
Hey @aadilhasan, i just encounter the bug signaled by lyvija ! Here you will ba able to reproduce: 
https://codesandbox.io/s/react-range-picker-zwq86

The range picker is working good. Yet if i double clic on the same day or clic on "Today" the end date is broken. Can you take a look at this please, i really need help :(

**Comment by aadilhasan** [comment]
@Kadrangelion I don't know somehow it is working fine for me, or i am not able to understand the problem, can you please make a demo video/gif so i can understand. you can mail it to me @ aadil.hasan07@gmail.com

**Comment by aadilhasan** [comment]
@Kadrangelion thanks for this i can see now what is wrong, i will try to fix it ASAP.
